version: '3.8'

volumes:
  cowrie-var:
    driver: local
  web-servie-log:
    driver: local
  rtsp-resource:
    driver: local
  node_modules:

services:
  cowrie_service:
    image: cowrie/cowrie:latest
    container_name: cowrie-services
    restart: unless-stopped
    env_file: ./.env
    environment:
      - COWRIE_LOCAL_PORT=$COWRIE_LOCAL_PORT
      - COWRIE_DOCKER_PORT=$COWRIE_DOCKER_PORT
    ports:
      - ${COWRIE_LOCAL_PORT}:${COWRIE_DOCKER_PORT}
    volumes:
      - cowrie-var:/cowrie/cowrie-git/var
      - ./cowrie-config/cowrie.cfg:/cowrie/cowrie-git/etc/cowrie.cfg
      - ./cowrie-config/motd:/cowrie/cowrie-git/honeyfs/etc/motd
  mysql_service:
    image: mysql:8.0.28
    container_name: mysql_service
    cap_add:
      - SYS_NICE
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQLDB_DATABASE
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
    volumes:
      - ./initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
  web_service:
    container_name: web_service
    depends_on:
      - mysql_service
    build: 
      context: ./webservices
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysql_service
      - DB_USER=$MYSQLDB_USER
      - DB_PASSWORD=$MYSQLDB_ROOT_PASSWORD
      - DB_NAME=$MYSQLDB_DATABASE
      - DB_PORT=$MYSQLDB_DOCKER_PORT
      - SESSION_SECRET=$SESSION_SECRET
      - JWT_SECRET=$JWT_SECRET
      - ADMIN_PATH=$ADMIN_PATH
      - DEFAULT_ADMIN_NAME=$DEFAULT_ADMIN_NAME
      - DEFAULT_ADMIN_PASSWORD=$DEFAULT_ADMIN_PASSWORD
      - TELEGRAM_CHAT_ID=$TELEGRAM_CHAT_ID
      - TELEGRAM_TOKEN=$TELEGRAM_TOKEN
      - EMAIL_ADDRESS=$EMAIL_ADDRESS
      - EMAIL_PASSWORD=$EMAIL_PASSWORD
      - EMAIL_ADDRESS_TARGET=$EMAIL_ADDRESS_TARGET
      - EMAIL_SERVICE=$EMAIL_SERVICE
      - EMAIL_HOST=$EMAIL_HOST
    ports:
      - "${NODE_LOCAL_PORT}:${NODE_DOCKER_PORT}"
    working_dir: /app/webservices
    volumes:
      - ./webservices:/app/webservices:rw
      - web-servie-log:/app/webservices/logs
      - node_modules:/app/webservices/node_modules
  rtsp_service:
    image: aler9/rtsp-simple-server
    container_name: rtsp_service
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MTX_PROTOCOLS=tcp
    ports:
      - ${RTSP_LOCAL_PORT}:${RTSP_DOCKER_PORT}
    volumes:
      - ./rtspservices/mediamtx.yml:/mediamtx.yml
      - ./videos:/app/rtsp/videos:rw
      - rtsp-resource:/app/rtsp
